export const saudiCities = [
    { ar: "الرياض", en: "Riyadh" },
    { ar: "جدة", en: "Jeddah" },
    { ar: "مكة المكرمة", en: "Makkah" },
    { ar: "المدينة المنورة", en: "Madinah" },
    { ar: "الدمام", en: "Dammam" },
    { ar: "الهفوف", en: "Al-Hofuf" },
    { ar: "الطائف", en: "Taif" },
    { ar: "تبوك", en: "Tabuk" },
    { ar: "بريدة", en: "Buraydah" },
    { ar: "خميس مشيط", en: "Khamis Mushait" },
    { ar: "أبها", en: "Abha" },
    { ar: "حائل", en: "Hail" },
    { ar: "الخبر", en: "Al-Khobar" },
    { ar: "الجبيل", en: "Al-Jubail" },
    { ar: "حفر الباطن", en: "Hafar Al-Batin" },
    { ar: "الخرج", en: "Al-Kharj" },
    { ar: "نجران", en: "Najran" },
    { ar: "ينبع", en: "Yanbu" },
    { ar: "القريات", en: "Al-Qurayyat" },
    { ar: "القطيف", en: "Al-Qatif" },
    { ar: "جيزان", en: "Jazan" },
    { ar: "سكاكا", en: "Sakaka" },
    { ar: "الباحة", en: "Al-Bahah" },
    { ar: "عرعر", en: "Arar" },
    { ar: "عنيزة", en: "Unaizah" },
    { ar: "الرس", en: "Ar Rass" },
    { ar: "صامطة", en: "Samtah" },
    { ar: "المجمعة", en: "Al Majma'ah" },
    { ar: "القويعية", en: "Al Quway'iyah" },
    { ar: "بيشة", en: "Bisha" },
    { ar: "أحد رفيدة", en: "Ahad Rafidah" },
    { ar: "الزلفي", en: "Al Zulfi" },
    { ar: "الظهران", en: "Dhahran" },
    { ar: "شرورة", en: "Sharurah" },
    { ar: "وادي الدواسر", en: "Wadi Ad-Dawasir" },
    { ar: "الدوقة", en: "Ad Duwadimi" },
    { ar: "عفيف", en: "Afif" },
    { ar: "طريف", en: "Turaif" },
    { ar: "رابغ", en: "Rabigh" },
    { ar: "محايل عسير", en: "Muhayil" },
    { ar: "النعيرية", en: "Nariyah" },
    { ar: "الخفجي", en: "Khafji" },
    { ar: "رفحاء", en: "Rafha" },
    { ar: "بقيق", en: "Abqaiq" },
    { ar: "العلا", en: "Al Ula" },
    { ar: "ضبا", en: "Duba" },
    { ar: "تيماء", en: "Tayma" },
    { ar: "الوجه", en: "Al Wajh" },
    { ar: "أملج", en: "Umluj" }
].sort((a, b) => a.ar.localeCompare(b.ar));
